### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by lucabenaventew** [lucabenaventew/space-travelers#21]
# Note
We are two people in the team, Daniel and Luca.
Here is the [link](https://github.com/lucabenaventew/space-travelers/projects/1) of the kanban board

# Project Updates
- [x] Created kanban board with all cards
![image](https://user-images.githubusercontent.com/85821183/192392818-857edf58-c77b-402b-b574-a36aad778ff8.png)
Kindly leave feedback about the project

**Comment by Davidosky007** [comment]
Hi @lucabenaventew @dgonzalesi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a link to your GitHub Kanban board project and a note telling the reviewer how many people there are in your team as stated in the [project requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=In%20its%20description,in%20your%20team.). 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Davidosky007** [comment]
Hi @lucabenaventew @dgonzalesi 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Proper issue descriptions with all the necessary information 👍 

## Required Changes ♻️
* Since you are a team of two people you should have 17 cards and not 13 as stated in the [project requirement ](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=If%20your%20group%20includes%20two%20people%20%2D%20remove%20all%20cards%20with%20Team3%20in%20the%20title.) after removing all the cards with team3 title which are 7 in number you should be left with 17 cards making all 24 cards in total, kindly correct this 🙏 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucabenaventew** [comment]
Kindly accept the project because my partner deleted all the team 3 related cards, we checked them one by one. Thank you

**Comment by descholar-ceo** [comment]
Hi @lucabenaventew && @dgonzalesi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all of the requested changes ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
